---
# Grant {{ APP_NAMESPACE_ADMIN }} namespace admin privileges
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: {{ APP_NAMESPACE_NAME }}
subjects:
- kind: User
  name: {{ APP_NAMESPACE_ADMIN }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

