---
# Define project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ APP_NAMESPACE_NAME }}
  labels:
    name: {{ APP_NAMESPACE_NAME }}

---
# Grant the authentication service access to pods in {{ APP_NAMESPACE_NAME }} namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dap-authn-service
  namespace: {{ APP_NAMESPACE_NAME }}
subjects:
- kind: ServiceAccount
  name: dap-authn-service
  namespace: cyberark
roleRef:
  kind: ClusterRole
  name: dap-authn-role
  apiGroup: rbac.authorization.k8s.io
